spring.application.name=industrialbrain-backend

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=YOUR_DATABASE_URL
spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# Gemini
# ===============================
gemini.api.keys=YOUR_GEMINI_KEY_1,YOUR_GEMINI_KEY_2,YOUR_GEMINI_KEY_3

# ===============================
# JWT
# ===============================
jwt.secret=YOUR_JWT_SECRET

spring.jpa.open-in-view=false

# ===============================
# Cloudinary
# ===============================
cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_CLOUDINARY_API_KEY
cloudinary.api-secret=YOUR_CLOUDINARY_API_SECRET

# ===============================
# OCR
# ===============================
tesseract.datapath=C:/Program Files/Tesseract-OCR/tessdata